version: '3'
services:
  frontend:
    build:
      context: ./frontend  # Path to your frontend Dockerfile
    ports:
      - "5173:5173"  # Map Vite's port
    environment:
      - VITE_API_URL=http://34.143.132.158:3000 # Docker service name as backend URL
    depends_on:
      - backend  # Ensure backend is started before frontend
    networks:
      - app-network

  backend:
    build:
      context: ./backend  # Path to your backend Dockerfile
    ports:
      - "3000:3000"  # Map backend port
    environment:
      - NODE_ENV=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge